# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the Egeria project.
---
logging:
  level: INFO

imageDefaults:
  registry: docker.io
  namespace: odpi
  tag: latest
  pullPolicy: IfNotPresent

egeria:
  user: myuser
  cohort: coco
  server: myserver

release:
  version: 2.2-SNAPSHOT
  repo: snapshot

image:
  egeria:
    name: egeria
    pullPolicy: Always

  configure:
    name: egeria-configure
    pullPolicy: Always

# NOTE: this image is "bring your own". Furthermore, the tag will be automatically built based on the
# name used for the Helm chart release + "-samples". So for example, if you deploy the Helm chart with
# a name of "v11.7.0.2" then the image tag used for deploying the IGC container will be "v11.7.0.2-samples"
# (if you wish to override this, change the "ibm-igc.yaml" definition directly)
  ibmigc:
    registry: "localhost:5000"
    namespace: ibm
    name: infosvr

ibmigc:
  user: isadmin
  password: isadmin
  proxyserver: ibmigc

kafka:
  securityContext:
    enabled: false
  zookeeper:
    persistence:
      enabled: false
  persistence:
    enabled: false
