# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
name: "Build"

# Trigger after code is merged. only on main repo
# - does not run on modification (may be just text)

on:
  push:
    branches: [main, release-*]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Merge"
    steps:
      - uses: actions/checkout@v2
        name: Checkout source
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          # Java 11 is used for merge builds (PRs do check Java latest)
          java-version: '11'
          distribution: 'adopt'
          # Publishing attributes for maven central (this step adds to setting.xml)
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          # Keys must be known to maven central - require broad publishing
          gpg-private-key: ${{ secrets.OSSRH_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      # Build and publish - but only for main
      - name: Build with Maven (Publish snapshots to maven central)
        if: ${{ github.repository == 'odpi/egeria-connector-ibm-information-server' && github.ref == 'refs/heads/main'}}
        # See https://github.com/actions/toolkit/issues/231 requires parms using . to be quoted
        run: 'mvn -B -DuseMavenCentral clean deploy'
        # Needed for publishing -- note we push to a staging area, login to oss.sonatype.org to
        # verify (close) the repository & release
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
          # Build and publish - but only for main
      - name: Build with Maven (no snapshots published)
        if: ${{ github.repository != 'odpi/egeria-connector-ibm-information-server' || github.ref != 'refs/heads/main'}}
        run: mvn -B clean verify
      # Mostly for verification - not published to the release itself for now
      - name: Upload assemblies
        uses: actions/upload-artifact@v2
        with:
          name: Assemblies
          path: |
            distribution/target/*.jar
            ia-clientlibrary/target/*.jar
            igc-clientlibrary/target/*.jar
